In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load the DataFrame
df = pd.read_csv("/home/inventor/Datasets/House Prediction/House_Prediction/data.csv")
df.head()

                  date      price  bedrooms  ...       city  statezip  country
0  2014-05-02 00:00:00   313000.0       3.0  ...  Shoreline  WA 98133      USA
1  2014-05-02 00:00:00  2384000.0       5.0  ...    Seattle  WA 98119      USA
2  2014-05-02 00:00:00   342000.0       3.0  ...       Kent  WA 98042      USA
3  2014-05-02 00:00:00   420000.0       3.0  ...   Bellevue  WA 98008      USA
4  2014-05-02 00:00:00   550000.0       4.0  ...    Redmond  WA 98052      USA

[5 rows x 18 columns]

In [3]:
df.shape

(4600, 18)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

In [5]:
df.head()

                  date      price  bedrooms  ...       city  statezip  country
0  2014-05-02 00:00:00   313000.0       3.0  ...  Shoreline  WA 98133      USA
1  2014-05-02 00:00:00  2384000.0       5.0  ...    Seattle  WA 98119      USA
2  2014-05-02 00:00:00   342000.0       3.0  ...       Kent  WA 98042      USA
3  2014-05-02 00:00:00   420000.0       3.0  ...   Bellevue  WA 98008      USA
4  2014-05-02 00:00:00   550000.0       4.0  ...    Redmond  WA 98052      USA

[5 rows x 18 columns]

In [6]:
# Remove the some columns
df.drop(columns=["date", "street", "statezip", "country"], axis=1, inplace=True)

In [7]:
# Change the Datatypes

df["price"] = df["price"].astype("int64")
df["bedrooms"] = df["bedrooms"].astype("int64")
df["bathrooms"] = df["bathrooms"].astype("int64")
df["floors"] = df["floors"].astype("int64")

In [8]:
df.head()

     price  bedrooms  bathrooms  ...  yr_built  yr_renovated       city
0   313000         3          1  ...      1955          2005  Shoreline
1  2384000         5          2  ...      1921             0    Seattle
2   342000         3          2  ...      1966             0       Kent
3   420000         3          2  ...      1963             0   Bellevue
4   550000         4          2  ...      1976          1992    Redmond

[5 rows x 14 columns]

In [9]:
num_cols = [col for col in df.columns if df[col].dtype in ["float64", "int64"]]
cat_cols = [col for col in df.columns if df[col].dtype not in ["float64", "int64"]]

In [10]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

normalizer = MinMaxScaler()

df[num_cols] = normalizer.fit_transform(df[num_cols])

In [11]:
df.head()

      price  bedrooms  bathrooms  ...  yr_built  yr_renovated       city
0  0.011771  0.333333      0.125  ...  0.482456      0.995531  Shoreline
1  0.089658  0.555556      0.250  ...  0.184211      0.000000    Seattle
2  0.012862  0.333333      0.250  ...  0.578947      0.000000       Kent
3  0.015795  0.333333      0.250  ...  0.552632      0.000000   Bellevue
4  0.020684  0.444444      0.250  ...  0.666667      0.989076    Redmond

[5 rows x 14 columns]

In [12]:
one_hot = OneHotEncoder(sparse_output=False, handle_unknown="ignore", drop="first")

encoder = one_hot.fit_transform(df[cat_cols])

encoded_df = pd.DataFrame(encoder, columns=one_hot.get_feature_names_out(cat_cols))

encoded_df = pd.concat([df, encoded_df], axis=1)

In [13]:
encoded_df.drop("city", axis=1, inplace=True)

In [14]:
encoded_df

         price  bedrooms  ...  city_Woodinville  city_Yarrow Point
0     0.011771  0.333333  ...               0.0                0.0
1     0.089658  0.555556  ...               0.0                0.0
2     0.012862  0.333333  ...               0.0                0.0
3     0.015795  0.333333  ...               0.0                0.0
4     0.020684  0.444444  ...               0.0                0.0
...        ...       ...  ...               ...                ...
4595  0.011590  0.333333  ...               0.0                0.0
4596  0.020095  0.333333  ...               0.0                0.0
4597  0.015679  0.333333  ...               0.0                0.0
4598  0.007649  0.444444  ...               0.0                0.0
4599  0.008296  0.333333  ...               0.0                0.0

[4600 rows x 56 columns]

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(encoded_df.drop("price", axis=1), encoded_df["price"], test_size=0.2, random_state=42)

In [16]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3680, 55), (920, 55), (3680,), (920,))

In [17]:
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

In [18]:
class Schostic_Gradient_Descent():

    def __init__(self, learning_rate, epochs):
        self.coef_ = None
        self.lr = learning_rate
        self.epochs = epochs
    
    def fit(self, X_train, y_train):
        X_train = np.insert(X_train, 0, 1, axis=1)

        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                
                idx = np.random.randint(0, X_train.shape[0])

                y_hat = np.dot(X_train[idx], self.coef_)

                error = y_train[idx] - y_hat

                self.coef_ = self.coef_ + (self.lr * error * X_train[idx])
        print(f"Coef_: {self.coef_}")
    
    def predict(self, X_test):
        X_test = np.insert(X_test, 0,1,axis=1)
        y_pred = np.dot(X_test, self.coef_)
        return y_pred

In [19]:
sgd = Schostic_Gradient_Descent(learning_rate=0.001, epochs=50)

In [20]:
sgd.fit(X_train, y_train)

Coef_: [-0.90187698 -0.14201932 -0.01751883  0.097137    0.74432332  0.02086961
  0.27828127 -0.08374529 -0.0141635   0.11412508  0.19452357 -0.01598916
 -0.00265735  0.9366476   0.99887222  0.94935085  0.97967587  0.94803204
  0.93963517  0.93650936  0.95716512  0.96306454  0.9415907   0.93043183
  0.92352519  0.94705497  0.93988947  1.          0.92347917  0.94521175
  0.94057503  0.95021208  0.95151646  0.94620462  0.94963332  0.92689404
  1.00115668  0.95054192  0.95751828  0.94876667  0.99586465  0.98552311
  0.98239548  0.93733495  0.94245669  0.93509953  0.96873271  0.95185379
  0.9544763   0.99254604  0.93689863  0.99527682  0.94609004  0.86410122
  0.91034156  0.988743  ]

In [21]:
y_pred = sgd.predict(X_test)

In [22]:
def r2_score_custom(y_true, y_pred):

    mean_value = np.mean(y_true)

    SSE = np.sum((y_true - y_pred) ** 2)
    TSS = np.sum((y_true - mean_value) ** 2)

    r2_score = 1 - (SSE / TSS)
    return r2_score

In [23]:
r2_score_c = r2_score_custom(y_test, y_pred)
r2_score_c

np.float64(-2.265447178702188)

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr = LinearRegression()

In [26]:
lr.fit(X_train, y_train)

LinearRegression()

In [27]:
y_pred_sk = lr.predict(X_test)

In [28]:
from sklearn.metrics import r2_score
r2_score_sk = r2_score(y_test, y_pred_sk)
r2_score_sk

-3770489068150380.5

In [29]:
lr.coef_, lr.intercept_

(array([-1.44734702e-02,  5.46975121e-03,  2.30507711e+10, -1.46735386e-03,
         1.71850898e-03,  1.83081763e-02,  7.13855717e-03,  4.59585741e-03,
        -1.58222453e+10, -8.43619716e+09, -4.62940302e-03,  2.44020951e-04,
         2.90587885e-04,  2.08010689e-02,  1.42333246e-02,  3.20662676e-03,
         4.64995211e-03,  1.91798933e-03,  2.95454558e-03,  2.94498633e-02,
         2.96640687e-04,  2.27422992e-04,  3.46120135e-03, -1.07417617e-03,
         7.00561836e-03, -6.02304852e-04, -7.07362107e+07,  7.36556595e-03,
         5.25843843e-03,  7.29461650e-04,  1.09831493e-02,  4.20137385e-03,
         1.35515428e-03,  4.31489944e-02,  1.87432766e-02,  6.73672557e-03,
         7.35425949e-03,  4.57477570e-03,  3.20887566e-03,  1.80912018e-03,
         3.23200226e-03,  9.53674316e-05,  9.76943970e-03,  2.27165222e-03,
         7.11965561e-03,  1.90496445e-03,  1.06391907e-02,  6.12640381e-03,
         2.84957886e-03,  1.83200836e-03,  8.61167908e-03,  3.58176231e-03,
         6.36100769e-04,  5.63430786e-03,  2.78379917e-02]),
 np.float64(-0.0008047479250996442))

In [30]:
from sklearn.metrics import mean_squared_error

In [31]:
mse = mean_squared_error(y_test, y_pred_sk)
mse

np.float64(5438708151565.407)

In [32]:
mse_c = mean_squared_error(y_test, y_pred)
mse_c

np.float64(0.004710215006146657)